import os

def get_flag(name: str, default: bool = False) -> bool:
    return os.environ.get(name, str(default)).lower() in ('true', '1', 'yes')

class FeatureFlags:
    ENABLE_LOCAL_FACTUAL = get_flag("ENABLE_LOCAL_FACTUAL", True)
    ENABLE_LOCAL_SUMMARIZATION = get_flag("ENABLE_LOCAL_SUMMARIZATION", False)
    ENABLE_RESERVED_LOCAL_WORKERS = get_flag("ENABLE_RESERVED_LOCAL_WORKERS", True)
    ENABLE_SHORT_FIREWORKS_PROMPTS = get_flag("ENABLE_SHORT_FIREWORKS_PROMPTS", True)
    ENABLE_DYNAMIC_MAX_TOKENS = get_flag("ENABLE_DYNAMIC_MAX_TOKENS", False)
    
    ENABLE_RESPONSE_COMPRESSION = get_flag("ENABLE_RESPONSE_COMPRESSION", False)
    ENABLE_ROUTER_FIX = get_flag("ENABLE_ROUTER_FIX", False)
    ENABLE_SMART_ROUTING_V2 = get_flag("ENABLE_SMART_ROUTING_V2", True)
    FIREWORKS_CONCURRENCY = int(os.environ.get("FIREWORKS_CONCURRENCY", "4"))
    
    ENABLE_DETERMINISTIC_EXTRACTION = get_flag("ENABLE_DETERMINISTIC_EXTRACTION", False)
    ENABLE_SPACY_NER = get_flag("ENABLE_SPACY_NER", True)
    ENABLE_LOCAL_SENTIMENT_QWEN = get_flag("ENABLE_LOCAL_SENTIMENT_QWEN", False)
    ENABLE_LOCAL_SUMMARIZATION_QWEN = get_flag("ENABLE_LOCAL_SUMMARIZATION_QWEN", True)
